{% set version = "1.18.1" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.zip
  sha256: e37802868ba5f389bf4e3f4c40c16e1b031814f0585ac122637de219de6279cb

build:
  number: 0
  skip: True  # [py27]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # gcc 7.3 segfaults on aarch64
    - clangdev    # [aarch64]
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python

{% set tests_to_skip = "_not_a_real_test" %}
# Slow tests, aarch64 doesn't have too much time on drone, skip
#{% set tests_to_skip = tests_to_skip + " or test_may_share_memory_easy_fuzz" %}    # [aarch64]
#{% set tests_to_skip = tests_to_skip + " or test_may_share_memory_harder_fuzz" %}  # [aarch64]
# Likely bugs in openblas????
# https://github.com/numpy/numpy/issues/14438#issuecomment-560940664
#{% set tests_to_skip = tests_to_skip + " or test_einsum_sums_cfloat64" %}  # [ppc64le]
# Only the complex256 system is failing, but I don't know how to skip it on its own
# # https://github.com/numpy/numpy/issues/15243
#{% set tests_to_skip = tests_to_skip + " or test_loss_of_precision" %}     # [ppc64le or aarch64]
# Probably needs too much memory on ppc64le and aarch64
{% set tests_to_skip = tests_to_skip + " or test_large_zip" %}   # [ppc64le or aarch64]

test:
  requires:
    - pytest
    - pytest-timeout
  commands:
    - f2py -h
    - export OPENBLAS_NUM_THREADS=1  # [unix]
    - set OPENBLAS_NUM_THREADS=1     # [win]
    - pytest --timeout 300 --verbose --pyargs numpy -k "not ({{ tests_to_skip }})"
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
