{% set version = "1.17.0" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: 47b7b6145e7ba5918ce26be25999b6d4b35cf9fbfdf46b7da50090ffdb020445

build:
  number: 0
  skip: True  # [py27]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # gcc 7.3 segfaults on aarch64
    - clangdev    # [aarch64]
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python

{% set skip_tests = [
    [aarch64 or ppc64le, 'test_loss_of_precision',              'Seems to fail on aarch64 and ppc64le'],
    [ppc64le,            'test_einsum_sums_cfloat64',           'expected failure ppc64le'],
    [aarch64,            'test_may_share_memory_easy_fuzz',     'Times out on qemu+aarch'],
    [aarch64,            'test_xerbla_override',                'Seems to timeout on aarch64'],
    [aarch64,            'test_may_share_memory_harder_fuzz',   'Seems to timeout on aarch64'],
    [aarch64,            'test_large_zip',                      'Seems to timeout on aarch64'],
    [aarch64,            'test_sdot_bug_8577',                  'hangs on aarch64'],
  ]
%}

test:
  requires:
    - pytest
    - pytest-timeout
  commands:
    - f2py -h
    - pytest --timeout=300 -v --pyargs numpy -k "not (conda_forge
{%- for skip_test in skip_tests -%}
{%- if skip_test[0] %} or {{ skip_test[1] }}{%- endif -%}
{%- endfor -%})"
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
