{% set version = "1.17.0" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: 47b7b6145e7ba5918ce26be25999b6d4b35cf9fbfdf46b7da50090ffdb020445
  patches:
    # Apparently not all glibcs have 128 bit precision floats implemented correctly.
    - skip_test_loss_of_precision.diff  # [aarch64 or ppc64le]
    - skip_test_mem_overlap.diff        # [aarch64]
    - skip_test_xerbla.diff             # [aarch64]
    - skip_test_einsum_cfloat64.diff    # [ppc64le]
    - skip_structured_object.diff       # [win and py27]

build:
  number: 0
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # gcc 7.3 segfaults on aarch64
    - clangdev    # [aarch64]
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python

test:
  requires:
    - pytest
    - pytest-timeout
  commands:
    - f2py -h
    - pytest --timeout=300 -v --pyargs numpy
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
